# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict

-   repo: local
    hooks:
    -   id: lint_typescript
        name: Check and fix typescript files
        files: \.tsx?$
        language: script
        stages: [commit]
        entry: scripts/eslint.sh
        pass_filenames: true
        verbose: true

    -   id: lint_json
        name: Check and fix json files
        files: \.json$
        language: system
        stages: [commit]
        entry: yarn prettier
        pass_filenames: true
